# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
  
variables:
  LANG: 'Python'
  VERSION: '3.7'
  OS: 'Windows'
  WORKFOLDER: 'D:\a\1\s\'
  BROWSERPATH: 'D:/a/1/s/node_modules/chromedriver/lib/chromedriver/chromedriver.exe'
  
jobs:

- job: 'Test'

  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install --upgrade robotframework robotframework-seleniumlibrary && npm install chromedriver
    displayName: 'Install dependencies'
  
  - powershell: robot --pythonpath . --variable BROWSERPATH:$(BROWSERPATH) -x outputxunit.xml TestCases.robot
    displayName: 'Run Robot Scripts'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: outputxunit.xml
      searchFolder: '$(WORKFOLDER)'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results outputxunit.xml'
      testResultsTitle: Automated Test for $(os_name) with Python $(VERSION)
      testRunTitle: $(LANG)-$(VERSION)-$(OS)-Automated Test
      