name: Test continue-on-error

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This step will pass"
      - name: Step 2
        id: step2
        continue-on-error: true
        run: echo "This step will fail" && exit 1
      - name: Step 3
        run: echo "And this step ..."
  after-test:
    runs-on: ubuntu-latest
    needs: [test]
