jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Robot Framework tests
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          robot --listener GHAReports:report_file=extra_summary.md --outputdir output Selenium.robot
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: robot-framework-report
          path: extra_summary.md
      - name: Show report
        uses: actions/upload-artifact@v3
        with:
          name: robot-framework-report
          path: output
