name: Support Robot Report 2

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  robot-tests-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework tests
        run: |
          robot Selenium.robot
        continue-on-error: true

      - name: Check Docker info
        if: always()
        run: docker info
        
      - name: Run Windows containers (native)
        run: |
          docker run --rm mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd /c echo "Windows container"
          docker run --rm mcr.microsoft.com/windows/servercore:ltsc2022 powershell -c "Write-Host 'PowerShell in container'"
          
      # Method 1: Using Robot Framework HTML reports (Recommended)
      - name: Publish Robot Framework Results
        uses: joonvena/robotframework-reporter-action@v2.4
        if: always()
        with:
          gh_access_token: ${{ secrets.MYTOKEN }}

      - name: Publish test output files
        if: success() || failure()
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Testing Outputs
          path: |
            *.png
            *.html
            *.zip
            *.xml

